Changed Rails to 4.2.11.17
Also installed sprockets due to the following rails installation error:

ERROR:  Error installing rails:
	The last version of sprockets (>= 3.0.0) to support your Ruby & RubyGems was 3.7.2. Try installing it with `gem install sprockets -v 3.7.2` and then running the current command again
	sprockets requires Ruby version >= 2.5.0. The current ruby version is 2.3.7.456.